# Generated by Django 4.2.9 on 2024-06-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """,
        """
            DELETE from store_collection
            WHERE title='collection1'
        """)
    ]
