# Generated by Django 4.2.9 on 2024-06-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240601_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
